[package]
name = "asn-core"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
asn-comm = { path = "../asn-comm" }
asn-argus = { path = "../asn-argus" }
asn-db = { path = "../asn-db" }
tokio = { version = "1", features = ["full"] }
once_cell = "1.21.1"
rand = "0.9.0"
